apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flask-daemonset
spec:
  selector:
    matchLabels:
      app: flask-hw-dms
  template:
    metadata:
      labels:
        app: flask-hw-dms
    spec:
      containers:
      - name: flask-hw
        image: artline0912/flask_hw:v1
        ports:
        - containerPort: 5000

