apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: flask-hw-depl
  labels:
    app: flask-hw-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hw-depl
  template:
    metadata:
      labels:
        app: flask-hw-depl
    spec:
      containers:
      - name: flask-hw-depl
        image: artline0912/flask_hw:v1
        ports:
        - containerPort: 5000
