apiVersion: v1
kind: Pod
metadata:
  name: flask-hw-pod
  labels:
    app: flask-hw
spec:
  containers:
    - name: flask-hw
      image: artline0912/flask_hw:v1
      ports:
        - containerPort: 5000
