apiVersion: v1
kind: Service
metadata:
  name: flask-hw
  namespace: flask-hw
spec:
  type: NodePort
  selector:
    app: flask-hw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31678
