apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-statefulset
spec:
  serviceName: headless-serv
  replicas: 1
  selector:
    matchLabels:
      app: flask-hw-sts
  template:
    metadata:
      labels:
        app: flask-hw-sts
    spec:
      containers:
        - name: flask-hw
          image: artline0912/flask_hw:v1
          ports:
            - containerPort: 5000
